version: '2.3'
services:
    discovery-server:
        container_name: discovery-server
        image: avandreev/discovery-server:latest
        ports:
            - 7001:7001
        networks:
            - network
        healthcheck:
            test: apk add curl && (curl --silent --fail discovery-server:7001 || exit 1)
            interval: 2s
            timeout: 5s
            retries: 30
                        
    config-server:
        container_name: config-server
        image: avandreev/config-server:latest
        ports:
            - 8001:8001
        networks:
            - network
        environment:
            - discovery.uri=discovery-server
        depends_on:
            discovery-server:
                condition: service_healthy
        healthcheck:
            test: apk add curl && (curl --silent --fail config-server:8001/actuator || exit 1)
            interval: 2s
            timeout: 5s
            retries: 30

    rest-server:
        container_name: rest-server
        image: avandreev/rest-server:latest
        ports:
            - 9601:9601
        networks:
            - network
        environment:
            - discovery.uri=discovery-server
        volumes:            
            - type: bind
              source: //C/dev/workspace/databases/h2-db.mv.db
              target: /C:/dev/workspace/databases/h2-db.mv.db
              volume:
                nocopy: false
        depends_on:
            config-server:
                condition: service_healthy
        healthcheck:
            test: apk add curl && (curl --silent --fail rest-server:9601 || exit 1)
            interval: 2s
            timeout: 5s
            retries: 30
            
    web-client:
        container_name: web-client
        image: avandreev/web-client:latest
        ports:
            - 9401:9401
        networks:
            - network
        environment:
            - discovery.uri=discovery-server
        depends_on:
            rest-server:
                condition: service_healthy
            
    hystrix-dashboard:
        container_name: hystrix-dashboard
        image: avandreev/hystrix-dashboard:latest
        ports:
            - 9301:9301
        networks:
            - network
        environment:
            - discovery.uri=discovery-server
        depends_on:
            config-server:
                condition: service_healthy
    
networks:
    network:
        driver: bridge  #overlay
# volumes:
    # h2-db:
        # external: true